name: Repository Garbage Collector

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  garbage-collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run git garbage collection
        run: git gc
